=== ndexbio/ndexutils/ndexutil/tsv/loading_plan_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "NDEx TSV Loading Plan",
    "description": "Loading plan used by TSV loader",

    "definitions": {

      "NodeMapping": {
        "type": "object",
        "properties": {
          "rep_prefix": {
            "description": "Prefix that need to be added to the id column",
            "type": "string"
          },
          "rep_column": {
           "description": "Column that will be used as the represent field of a node. The first non-empty value in the list will be used to populate the node represent field.",
            "type": "string"
          },
          "node_name_column": {
            "description": "The name of a node. If id_column is missing in this object, the node_name will be used as a unique id of a node. This version of TSV loader requires node name to be unique in a network",
            "type": "string"
          },
          "property_columns": {
            "description": "Defines the mapping of all node properties. An Each of the non-empty value in these columns ",
            "type": "array",
            "items" : { "oneOf": [
              {"type" : "string"},
              {"type" : "object",
                "properties": {
                  "column_name": {
                      "description": "name of the column in the spreadsheet",
                      "type":"string"
                    },
                  "attribute_name": {
                      "description": "attribute_name this column maps to",
                      "type": "string"
                  },
                  "value_prefix": {
                      "description": "prefix that need to be added to the values of this attributes(without colon).",
                      "type": "string"
                  },
                  "data_type": {
                      "description": "data type of the attribute values, default is string",
                      "type": "string",
                      "enum": ["string", "double", "boolean", "integer" ,"long", "list_of_string",
                          "list_of_double", "list_of_boolean", "list_of_integer", "list_of_long"]
                  },
                  "delimiter": {
                      "description": "delimiter character for array data types",
                      "type": "string"
                  },
                  "default_value": {
                    "description": "default value of this property when column_name is missing or the value in that column is missing",
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "anyOf": [
                  {
                    "type":"object",
                    "required": ["column_name"]
                  },
                  {
                    "type":"object",
                    "required": ["attribute_name"]
                  }
                ]
              }
             ]
            }
          }

        },
        "additionalProperties": false,
        "anyOf": [
            {
              "type":"object",
              "required": ["id_column"]
            },
            {
              "type":"object",
              "required": ["node_name_column"]
            }
          ]
      }

    },

    "type": "object",
    "properties": {
        "context": {
          "description": "Declare the namespaces that are used in this TSV file.",
          "type": "object",
           "patternProperties": {
                "^[^/@\\$\\^]+$": {
                  "type": "string",
                  "format": "uniref"
                }
            },
            "additionalProperties": false
        },
        "source_plan": {
            "description": "Mapping of the source nodes",
            "$ref": "#/definitions/NodeMapping"
        },
        "target_plan": {
             "description": "Mapping of the target nodes",
            "$ref": "#/definitions/NodeMapping"
        },
        "edge_plan": {
          "type": "object",
          "properties": {
            "default_predicate": {
              "description": "default value for edge name (interaction name).",
              "type": "string"
            },
            "predicate_id_column": {
              "description": "column that specify the edge name. If the value in this cell is missing, we will use the value defined in 'defalut_predicate', if it exists.",
              "type": "string"
            },
            "predicate_prefix": {
              "type": "string"
            },
            "citation_id_column": {
              "description": "column that specify the edge name. If the value in this cell is missing, we will use the value defined in 'defalut_predicate', if it exists.",
              "type": "string"
            },
            "citation_id_prefix": {
              "type": "string"
            },
            "property_columns": {
              "type": "array",
              "items": { "oneOf": [
              {"type" : "string"},
              {"type" : "object",
                "properties": {
                  "column_name": {
                      "description": "name of the column in the spreadsheet",
                      "type":"string"
                    },
                  "attribute_name": {
                      "description": "attribute_name this column maps to",
                      "type": "string"
                  },
                  "value_prefix": {
                      "description": "prefix that need to be added to the values of this attributes(without colon).",
                      "type": "string"
                  },
                  "data_type": {
                      "description": "data type of the attribute values, default is string",
                      "type": "string",
                      "enum": ["string","double","float", "boolean", "char","integer","long","short","list_of_string",
                          "list_of_double", "list_of_float","list_of_boolean", "list_of_integer", "list_of_long"]
                  },
                  "delimiter": {
                      "description": "delimiter character for array data types",
                      "type": "string"
                  },
                  "default_value": {
                    "description": "default value of this property when column_name is missing or the value in that column is missing",
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "anyOf": [
                  {
                    "type":"object",
                    "required": ["column_name"]
                  },
                  {
                    "type":"object",
                    "required": ["attribute_name"]
                  }
                ]
              }
             ]
            }
            }
          },
          "additionalProperties": false

        }

    },
    "additionalProperties": false,
    "required": ["source_plan","target_plan","edge_plan"]

}

=== ndexbio/ndexutils/tests/tsv/BRCA-2012-loadplan.json
{
    "context": {
        "pubmed": "http://identifiers.org/pubmed/",
        "chebi": "http://identifiers.org/chebi/CHEBI:",
        "uniprot": "http://identifiers.org/uniprot/",
        "cas": "http://identifiers.org/cas/",
        "kegg.compound": "http://identifiers.org/kegg.compound/",
        "hprd": "http://identifiers.org/hprd/"
    },
    "source_plan":
    {
        "node_name_column": "SOURCE",
        "property_columns": [
             {
                  "column_name": "NODE_TYPE",
                  "attribute_name": "type"
             },
            {
                  "column_name": "POSX",
                  "attribute_name": "POSX"
            },
            {
                  "column_name": "POSY--",
                  "attribute_name": "POSY"
            }
        ]
    },
    "target_plan":
    {
        "node_name_column": "TARGET",
        "property_columns": [
             {
                  "column_name": "NODE_TYPE_B",
                  "attribute_name": "type"
             },
            {
                  "column_name": "POSX_B",
                  "attribute_name": "POSX"
            },
            {
                  "column_name": "POSY--_B",
                  "attribute_name": "POSY"
            }
        ]
    },
    "edge_plan":
    {
        "default_predicate": "unknown",
        "predicate_id_column": "EDGE_TYPE"
    }
}

=== ndexbio/ndexutils/ndexutil/tsv/test/signor_load_plan.json
{
    "context": {
        "signor": "http://signor.uniroma2.it/relation_result.php?id=",
        "BTO": "http://identifiers.org/bto/BTO:",
        "uniprot": "http://identifiers.org/uniprot/",
        "PMID": "http://identifiers.org/pubmed/",
        "cid": "http://identifiers.org/pubchem.compound/",
        "sid": "http://identifiers.org/pubchem.substance/"
    },
    "source_plan":
    {
        "rep_prefix": "uniprot",
        "rep_column": "IDA",
        "node_name_column": "ENTITYA",
        "property_columns":
           [
               {
                    "column_name": "TYPEA",
                    "attribute_name": "TYPE"
                }
           ]
    },
    "target_plan":
    {
        "rep_prefix": "uniprot",
        "rep_column": "IDB",
        "node_name_column": "ENTITYB",
        "property_columns":
           [
               {
                    "column_name": "TYPEB",
                    "attribute_name": "TYPE"
                }
           ]
    },
    "edge_plan":
    {
        "default_predicate": "correlation",
        "predicate_id_column": "EFFECT",
        "citation_id_column": "PMID",
        "citation_id_prefix": "pubmed",
        "property_columns": [
               {
                    "column_name": "MECHANISM",
                    "attribute_name": "MECHANISM"
                },
               {
                    "column_name": "RESIDUE",
                    "attribute_name": "RESIDUE"
                },
               {
                    "column_name": "SEQUENCE",
                    "attribute_name": "SEQUENCE"
                },
               {
                    "column_name": "TAX_ID",
                    "attribute_name": "TAX_ID",
                    "data_type": "string"
                },
               {
                    "column_name": "CELL_DATA",
                    "attribute_name": "CELL_DATA"
                },
               {
                    "column_name": "TISSUE_DATA",
                    "attribute_name": "TISSUE_DATA"
                },
               {
                    "column_name": "DIRECT",
                    "attribute_name": "DIRECT"
                },
               {
                    "column_name": "NOTES",
                    "attribute_name": "NOTES"
                },
               {
                    "column_name": "ANNOTATOR",
                    "attribute_name": "ANNOTATOR"
                },
               {
                    "column_name": "SENTENCE",
                    "attribute_name": "SENTENCE"
                }
        ]
    }
}
